// var value1 = 5;
// var value2 = 3;
// var total = value1 + value2;
// document.write(`sum of 5 and 3= `+ total);
// var movieticket = 600;
// var buyTicket = 5;
// var total = 600*5;
// document.write(`total cost to buy is movie`+ total)
var tabel = 4;
var value = 1;
var total1 = tabel*value;
var tabel = 4;
var value = 2;
var total2 = tabel*value;
var tabel = 4;
var value = 3;
var total3 = tabel*value;
var tabel = 4;
var value = 4;
var total4 = tabel*value;
var tabel = 4;
var value = 5;
var total5 = tabel*value;
var tabel = 4;
var value = 6;
var total6 = tabel*value;
var tabel = 4;
var value = 7;
var total7 = tabel*value;
var tabel = 4;
var value = 8;
var total8 = tabel*value;
var tabel = 4;
var value = 9;
var total9 = tabel*value;
var tabel = 4;
var value = 10;
var total10 = tabel*value;
document.write(`<h1>Tabel of 4</h1>`)
document.write(`4x1= `+total1 + "</br>")
document.write(`4x2= `+total2 + "</br>")
document.write(`4x3= `+total3 + "</br>")
document.write(`4x4= `+total4 + "</br>")
document.write(`4x5= `+total5 + "</br>")
document.write(`4x6= `+total6 + "</br>")
document.write(`4x7= `+total7 + "</br>")
document.write(`4x8= `+total8 + "</br>")
document.write(`4x9= `+total9 + "</br>")
document.write(`4x10= `+total10 + "</br>")